In [3]:
from preprocessing import PrepareData

In [4]:
import pandas as pd

In [5]:
ppd = PrepareData()

In [7]:
df_train = ppd.get_train_data()

In [8]:
df_train.shape

(1460, 249)

In [21]:
df_train

,Id,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,ExterCond,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,Street_Grvl,Street_Pave,Utilities_AllPub,Utilities_NoSeWa,SalePrice
0,1,65.000000,8450,7,5,2003,2003,196.0,4,3,...,0,0,0,0,1,0,1,1,0,208500
1,2,80.000000,9600,6,8,1976,1976,0.0,3,3,...,0,0,0,0,1,0,1,1,0,181500
2,3,68.000000,11250,7,5,2001,2002,162.0,4,3,...,0,0,0,0,1,0,1,1,0,223500
3,4,60.000000,9550,7,5,1915,1970,0.0,3,3,...,0,0,0,0,1,0,1,1,0,140000
4,5,84.000000,14260,8,5,2000,2000,350.0,4,3,...,0,0,0,0,1,0,1,1,0,250000
5,6,85.000000,14115,5,5,1993,1995,0.0,3,3,...,0,0,0,0,1,0,1,1,0,143000
6,7,75.000000,10084,8,5,2004,2005,186.0,4,3,...,0,0,0,0,1,0,1,1,0,307000
7,8,70.049958,10382,7,6,1973,1973,240.0,3,3,...,0,0,0,0,1,0,1,1,0,200000
8,9,51.000000,6120,7,5,1931,1950,0.0,3,3,...,0,0,0,0,1,0,1,1,0,129900
9,10,50.000000,7420,5,6,1939,1950,0.0,3,3,...,0,0,0,0,1,0,1,1,0,118000
10,11,70.000000,11200,5,5,1965,1965,0.0,3,3,...,0,0,0,0,1,0,1,1,0,129500
11,12,85.000000,11924,9,5,2005,2006,286.0,5,3,...,0,0,1,0,0,0,1,1,0,345000
12,13,70.049958,12968,5,6,1962,1962,0.0,3,3,...,0,0,0,0,1,0,1,1,0,144000
13,14,91.000000,10652,7,5,2006,2007,306.0,4,3,...,0,0,1,0,0,0,1,1,0,279500
14,15,70.049958,10920,6,5,1960,1960,212.0,3,3,...,0,0,0,0,1,0,1,1,0,157000
15,16,51.000000,6120,7,8,1929,2001,0.0,3,3,...,0,0,0,0,1,0,1,1,0,132000
16,17,70.049958,11241,6,7,1970,1970,180.0,3,3,...,0,0,0,0,1,0,1,1,0,149000
17,18,72.000000,10791,4,5,1967,1967,0.0,3,3,...,0,0,0,0,1,0,1,1,0,90000
18,19,66.000000,13695,5,5,2004,2004,0.0,3,3,...,0,0,0,0,1,0,1,1,0,159000
19,20,70.000000,7560,5,6,1958,1965,0.0,3,3,...,0,0,0,0,0,0,1,1,0,139000
20,21,101.000000,14215,8,5,2005,2006,380.0,4,3,...,0,0,1,0,0,0,1,1,0,325300
21,22,57.000000,7449,7,7,1930,1950,0.0,3,3,...,0,0,0,0,1,0,1,1,0,139400
22,23,75.000000,9742,8,5,2002,2002,281.0,4,3,...,0,0,0,0,1,0,1,1,0,230000
23,24,44.000000,4224,5,7,1976,1976,0.0,3,3,...,0,0,0,0,1,0,1,1,0,129900
24,25,70.049958,8246,5,8,1968,2001,0.0,3,4,...,0,0,0,0,1,0,1,1,0,154000
25,26,110.000000,14230,8,5,2007,2007,640.0,4,3,...,0,0,0,0,1,0,1,1,0,256300
26,27,60.000000,7200,5,7,1951,2000,0.0,3,3,...,0,0,0,0,1,0,1,1,0,134800
27,28,98.000000,11478,8,5,2007,2008,200.0,4,3,...,0,0,0,0,1,0,1,1,0,306000
28,29,47.000000,16321,5,6,1957,1997,0.0,3,3,...,0,0,0,0,1,0,1,1,0,207500
29,30,60.000000,6324,4,6,1927,1950,0.0,3,3,...,0,0,0,0,1,0,1,1,0,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60.000000,21930,5,5,2005,2005,0.0,4,3,...,0,0,0,0,1,0,1,1,0,192140
1431,1432,70.049958,4928,6,6,1976,1976,0.0,3,3,...,0,0,0,0,1,0,1,1,0,143750
1432,1433,60.000000,10800,4,6,1927,2007,0.0,3,3,...,0,0,0,0,1,0,1,1,0,64500
1433,1434,93.000000,10261,6,5,2000,2000,318.0,3,3,...,0,0,0,0,1,0,1,1,0,186500
1434,1435,80.000000,17400,5,5,1977,1977,0.0,3,3,...,0,0,0,0,1,0,1,1,0,160000
1435,1436,80.000000,8400,6,9,1962,2005,237.0,4,4,...,0,0,0,0,0,0,1,1,0,174000
1436,1437,60.000000,9000,4,6,1971,1971,0.0,3,3,...,0,0,0,0,1,0,1,1,0,120500
1437,1438,96.000000,12444,8,5,2008,2008,426.0,5,3,...,0,0,1,0,0,0,1,1,0,394617
1438,1439,90.000000,7407,6,7,1957,1996,0.0,3,3,...,0,0,0,0,1,0,1,1,0,149700
1439,1440,80.000000,11584,7,6,1979,1979,96.0,3,3,...,0,0,0,0,1,0,1,1,0,197000
1440,1441,79.000000,11526,6,7,1922,1994,0.0,3,3,...,0,0,0,0,1,0,1,1,0,191000
1441,1442,70.049958,4426,6,5,2004,2004,147.0,4,3,...,0,0,0,0,1,0,1,1,0,149300
1442,1443,85.000000,11003,10,5,2008,2008,160.0,5,3,...,0,0,0,0,1,0,1,1,0,310000
1443,1444,70.049958,8854,6,6,1916,1950,0.0,3,3,...,0,0,0,0,1,0,1,1,0,121000
1444,1445,63.000000,8500,7,5,2004,2004,106.0,4,3,...,0,0,0,0,1,0,1,1,0,179600
1445,1446,70.000000,8400,6,5,1966,1966,0.0,3,3,...,0,0,0,0,1,0,1,1,0,129000
1446,1447,70.049958,26142,5,7,1962,1962,189.0,3,3,...,0,0,0,0,1,0,1,1,0,157900
1447,1448,80.000000,10000,8,5,1995,1996,438.0,4,3,...,0,0,0,0,1,0,1,1,0,240000
1448,1449,70.000000,11767,4,7,1910,2000,0.0,3,3,...,0,0,0,0,1,0,1,1,0,112000
1449,1450,21.000000,1533,5,7,1970,1970,0.0,3,3,...,0,0,0,0,1,0,1,1,0,92000
1450,1451,60.000000,9000,5,5,1974,1974,0.0,3,3,...,0,0,0,0,1,0,1,1,0,136000
1451,1452,78.000000,9262,8,5,2008,2009,194.0,4,3,...,0,0,1,0,0,0,1,1,0,287090
1452,1453,35.000000,3675,5,5,2005,2005,80.0,3,3,...,0,0,0,0,1,0,1,1,0,145000
1453,1454,90.000000,17217,5,5,2006,2006,0.0,3,3,...,0,0,0,0,1,0,1,1,0,84500
1454,1455,62.000000,7500,7,5,2004,2005,0.0,4,3,...,0,0,0,0,1,0,1,1,0,185000
1455,1456,62.000000,7917,6,5,1999,2000,0.0,3,3,...,0,0,0,0,1,0,1,1,0,175000
1456,1457,85.000000,13175,6,6,1978,1988,119.0,3,3,...,0,0,0,0,1,0,1,1,0,210000
1457,1458,66.000000,9042,7,9,1941,2006,0.0,5,4,...,0,0,0,0,1,0,1,1,0,266500
1458,1459,68.000000,9717,5,6,1950,1996,0.0,3,3,...,0,0,0,0,1,0,1,1,0,142125
1459,1460,75.000000,9937,5,6,1965,1965,0.0,4,3,...,0,0,0,0,1,0,1,1,0,147500